title: Жизнь в Германии
markdown: kramdown

# https://zendesk.github.io/jekyll-theme-zendesk-garden/getting_started.html
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: true
sidebar:
  - find-an-apartment
  - exchange-currency
  - request-kz-passport
  - transfer-drivers-license
  - invite-relatives

