title: KazGer
markdown: kramdown

# https://zendesk.github.io/jekyll-theme-zendesk-garden/getting_started.html
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: true
auto_page_title: false
sidebar:
  - label: Статьи 
    children:
      - travel-for-medical-care
      # - find-an-apartment
      - exchange-currency
      - purchase-medical-insurance
      #- request-kz-passport
      #- register-child-birth
      #- transfer-drivers-license
      - request-negativbescheinigung
      - invite-relatives
  - label: Полезные ссылки
    children:
      - translators
      - embassies
      #- national-cuisine

